// This file is automatically generated. Do not modify it manually.

package main

import (
	"encoding/json"
	"strings"

	"github.com/mattermost/mattermost/server/public/model"
)

var manifest *model.Manifest

const manifestStr = `
{
  "id": "com.mattermost.langflow",
  "name": "Langflow",
  "description": "Langflow flow와 1:1로 연결된 전용 Mattermost 봇을 통해 스트리밍 AI 응답을 제공합니다.",
  "homepage_url": "https://github.com/hkjang/mattermost-langflow-plugin",
  "support_url": "https://github.com/hkjang/mattermost-langflow-plugin/issues",
  "icon_path": "assets/starter-template-icon.svg",
  "version": "0.1.19-dev",
  "min_server_version": "10.0.0",
  "server": {
    "executables": {
      "darwin-amd64": "server/dist/plugin-darwin-amd64",
      "darwin-arm64": "server/dist/plugin-darwin-arm64",
      "linux-amd64": "server/dist/plugin-linux-amd64",
      "linux-arm64": "server/dist/plugin-linux-arm64",
      "windows-amd64": "server/dist/plugin-windows-amd64.exe"
    },
    "executable": ""
  },
  "webapp": {
    "bundle_path": "webapp/dist/main.js"
  },
  "settings_schema": {
    "header": "",
    "footer": "",
    "settings": [
      {
        "key": "Config",
        "display_name": "",
        "type": "custom",
        "help_text": "",
        "placeholder": "",
        "default": null,
        "hosting": "",
        "secret": false
      }
    ],
    "sections": null
  }
}
`

func init() {
	_ = json.NewDecoder(strings.NewReader(manifestStr)).Decode(&manifest)
}
